### PR TITLE
Allow PHP 8.0

### PR DESCRIPTION
**Pull request by sanmai**

### CODE REVIEW

**Comment by OndraM** [comment]
Hi @sanmai , thanks for the PR, but there is already [a branch](https://github.com/OndraM/ci-detector/tree/feature/php-8-dev) for this and failed build: https://github.com/OndraM/ci-detector/runs/1038567588?check_suite_focus=true

As you can see, there are some dev-dependencies which does not yet support PHP 8, namely [php-coveralls](https://github.com/php-coveralls/php-coveralls/issues/281) and lmc/coding-standard. As they are both dev-dependencies, I can try introduce some workaround to ignore them to make the build working PHP 8.0.

**Comment by sanmai** [comment]
I see. You could try `--ignore-platform-reqs` then, what do you think?

(I wish there was a PR for that branch, then I wouldn't miss it)

**Comment by sanmai** [comment]
I think I did something like that with `--ignore-platform-reqs` for another project, if this waits until later next week I think I can manage to find the ends.

**Comment by OndraM** [comment]
> (I wish there was a PR for that branch, then I wouldn't miss it)

Yep, sorry, I just tried the update recently and seen those issues so I decided to put in on hold for a while.

I'm now trying to deal with those issues (also phpunit is involved, because its dependency prophecy/prophecy does not yet have release with PHP 8 tagged). So something like `--ignore-platform-reqs` is probably inevitable. I will have a look.

**Comment by sanmai** [comment]
And, done!

**Comment by sanmai** [comment]
Alright, this is it. I hope you squash-merge this mess of commits.

**Comment by sanmai** [comment]
@OndraM any time you're ready.

**Review by OndraM — APPROVED** [review]

**Comment by OndraM** [comment]
Thanks a lot, @sanmai!

**Comment by sanmai** [comment]
No problem! 

Can you punch out a matching release? It is not a BC break, minor version should be fine.

**Comment by OndraM** [comment]
Yep, I already did new release :ok_hand: .

**Pull request merged**
