### PR TITLE
Add support for getting repository name

### LINKED ISSUE #14: Detect build/project name
CI project name could be detected as well.

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by drupol** [comment]
Why not throwing a custom exception when it's not supported ? (like `UnsupportedCIException`)

**Comment by Lctrs** [comment]
@drupol I'm all for it. This could be the subject of another PR. But this would be a BC break. So this decision needs the approval of @OndraM. I can work on it if he's okay.

**Comment by drupol** [comment]
Fair enough.

**Review by drupol — APPROVED** [review]
:+1:

**Comment by OndraM** [comment]
> Why not throwing a custom exception when it's not supported ? (like `UnsupportedCIException`)

If a property is not provided by some CI, I don't think it should be considered exceptional (ie. error/failure) state - it is expected that not all of them could be available.

Also see https://wiki.c2.com/?DontUseExceptionsForFlowControl

**Comment by Lctrs** [comment]
@OndraM In our case, I don't find that

```php
$buildNumber = $ci->getBuildNumber();
if ($buildNumber === '') {
	return;
}


$buildUrl = $ci->getBuildUrl();
if ($buildUrl === '') {
	return;
}

...
```

is clearer than

```php
try {
	$buildNumber = $ci->getBuildNumber();
	$buildUrl = $ci->getBuildUrl();
	...
} catch (UnsupportedCI $e) {
	return;
}
```

But maybe that's just me.

**Review by OndraM — APPROVED** [review]
:+1: Thanks for the contribution, LGTM!

**Pull request merged**
